############# JIRA #############
# jira_add_comment
# jira_add_worklog
# jira_batch_create_issues
# jira_batch_get_changelogs
# jira_create_issue
# jira_create_issue_link
# jira_create_sprint
# jira_delete_issue
# jira_download_attachments
# jira_get_agile_boards
# jira_get_board_issues
# jira_get_issue
# jira_get_link_types
# jira_get_project_issues
# jira_get_project_versions
# jira_get_sprint_issues
# jira_get_sprints_from_board
# jira_get_transitions
# jira_get_user_profile
# jira_get_worklog
# jira_link_to_epic
# jira_remove_issue_link
# jira_search
# jira_search_fields
# jira_transition_issue
# jira_update_issue
# jira_update_sprint